AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Root stack

Parameters:
  Stage:
    Type: String
    Default: "dev"
    AllowedValues: 
      - dev
      - staging
      - prod
      
Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yaml


  # Application:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: template.yaml

  ApplicationStack:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: template.yaml
        Parameters:
          Stage: !Ref Stage
          VpcId: !GetAtt VpcStack.Outputs.CustomVPCId
          SubnetId1: !GetAtt VpcStack.Outputs.PrivateSubnet1Id
          SubnetId2: !GetAtt VpcStack.Outputs.PrivateSubnet2Id
          RouteTableId: !GetAtt VpcStack.Outputs.PrivateRouteTableId
          SecurityGroupId: !GetAtt VpcStack.Outputs.CustomSecurityGroupId
        

Outputs:
  EndpointUrl:
   Value: !GetAtt ApplicationStack.Outputs.Url