version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1u4l6610al32b"
s3_prefix = "test-stack"
region = "us-east-1"
confirm_changeset = true
disable_rollback = true
capabilities = "CAPABILITY_AUTO_EXPAND"
image_repositories = []
